### ISSUE TITLE
Wrong baseline?

### ISSUE THREAD

**Issue by htdag** [vladimirgamalyan/fontbm#8]
![test1](https://user-images.githubusercontent.com/40710867/90282551-c03f7180-de98-11ea-9df2-2577171bd78b.png)
Just compare fontbm vs BMFont vs Hiero, chars: `A Á Â Ấ Ắ Ễ Ỗ`
From image, I found some issues
- Glyph rendered, not good as Hiero (freetype).
- The baseline seem wrong
BMFont: size=-48, lineHeight=56 base=44
fontbm: size=48, lineHeight=57 base=36

fontbm
```
info face="Consolas" size=48 bold=0 italic=0 charset="" unicode=1 stretchH=0 smooth=0 aa=1 padding=0,0,0,0 spacing=0,0 outline=0
common lineHeight=57 base=36 scaleW=512 scaleH=384 pages=1 packed=0 alphaChnl=0 redChnl=0 greenChnl=0 blueChnl=0
page id=0 file="consola_0.png"
chars count=8
char id=32 x=0 y=0 width=0 height=0 xoffset=0 yoffset=0 xadvance=26 page=0 chnl=15
char id=65 x=0 y=181 width=27 height=31 xoffset=0 yoffset=5 xadvance=26 page=0 chnl=15
char id=193 x=25 y=45 width=27 height=39 xoffset=0 yoffset=-3 xadvance=26 page=0 chnl=15
char id=194 x=27 y=0 width=27 height=39 xoffset=0 yoffset=-3 xadvance=26 page=0 chnl=15
char id=7844 x=0 y=92 width=27 height=43 xoffset=0 yoffset=-7 xadvance=26 page=0 chnl=15
char id=7854 x=0 y=0 width=27 height=45 xoffset=0 yoffset=-9 xadvance=26 page=0 chnl=15
char id=7876 x=0 y=135 width=19 height=46 xoffset=4 yoffset=-10 xadvance=26 page=0 chnl=15
char id=7894 x=0 y=45 width=25 height=47 xoffset=1 yoffset=-10 xadvance=26 page=0 chnl=15
kernings count=0
```
bmfont
```
info face="Consolas" size=-48 bold=0 italic=0 charset="" unicode=1 stretchH=100 smooth=1 aa=1 padding=0,0,0,0 spacing=0,0 outline=0
common lineHeight=56 base=44 scaleW=256 scaleH=256 pages=1 packed=0 alphaChnl=0 redChnl=4 greenChnl=4 blueChnl=4
page id=0 file="consola2_0.png"
chars count=8
char id=32   x=179   y=0     width=3     height=1     xoffset=-1    yoffset=55    xadvance=26    page=0  chnl=15
char id=65   x=152   y=0     width=27    height=31    xoffset=0     yoffset=13    xadvance=26    page=0  chnl=15
char id=193  x=98    y=0     width=27    height=39    xoffset=0     yoffset=5     xadvance=26    page=0  chnl=15
char id=194  x=125   y=0     width=27    height=39    xoffset=0     yoffset=5     xadvance=26    page=0  chnl=15
char id=7844 x=71    y=0     width=27    height=43    xoffset=0     yoffset=1     xadvance=26    page=0  chnl=15
char id=7854 x=25    y=0     width=27    height=44    xoffset=0     yoffset=0     xadvance=26    page=0  chnl=15
char id=7876 x=52    y=0     width=19    height=44    xoffset=4     yoffset=0     xadvance=26    page=0  chnl=15
char id=7894 x=0     y=0     width=25    height=45    xoffset=1     yoffset=0     xadvance=26    page=0  chnl=15
```

Please take a look,
Thanks.

**Comment by vladimirgamalyan** [comment]
Fixed and released, thank you and sorry for the late reply =)
(baseline is still different from BMFont version, the last one slightly crop some glyphs, for example Consolas `Ỗ` as you can see on your screenshot)

**Comment by 0xDC00** [comment]
![image](https://user-images.githubusercontent.com/29352751/116976965-0b7e0680-acec-11eb-9a0b-6775fda6ea6d.png)

Thanks, but it still not correct.

**Comment by htdag** [comment]
![image](https://user-images.githubusercontent.com/29352751/116976965-0b7e0680-acec-11eb-9a0b-6775fda6ea6d.png)

Thanks, but it still not correct (char g).

**Comment by vladimirgamalyan** [comment]
I guess you use common/lineHeight parameter for your canvas height, so bottom of 'g' doesn't fit into the picture. Actually lineHeight means how far the cursor should be moved vertically when moving to the next line (see http://www.angelcode.com/products/bmfont/doc/render_text.html). To calculate required canvas height you can get the maximum value out of all yoffset + height.

**Comment by vladimirgamalyan** [comment]
I added the `--extra-info` flag, it adds a common/totalHeight value that you can use as total canvas height to fit any glyphs from the font.

**Comment by htdag** [comment]
I use lineHeight
But, it displays correctly for bmfont.

**Comment by vladimirgamalyan** [comment]
BMFont [uses](https://github.com/kylawl/bmfont/blob/8234e2133d47e190088e1b6864c318c6fcf071ef/source/fontgen.cpp#L1584) [TEXTMETRIC.tmAscent](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-textmetrica) as common/base value (without TEXTMETRIC.tmInternalLeading) and crops top of glyphs above this value:

![image](https://user-images.githubusercontent.com/12879954/144344198-651792d3-b9af-4839-bec3-6dc7250b9ba0.png)

As result of this cropping - you could fit your text in lineHeight.

fontbm uses distance from topmost possible pixel (for all font glyphs) to baseline as common/base, so it is not the same value as BMFont, and rendered text looks below a bit (to fit all accent marks and other diacritical characters), but in this case lineHeight is not enough to fit all the glyphs and should be used only as distance between baselines.

**Comment by vladimirgamalyan** [comment]
[The last release](https://github.com/vladimirgamalyan/fontbm/releases/tag/v0.5.0) generates more similar base values, maybe this will suit your case.
